---
language: ruby

script:
  - bundle exec rake test

rvm:
  - 2.1
  - 2.4
  - 2.5
  - 2.6
  - 2.7

deploy:
  provider: rubygems
  api_key:
    secure: Rm6j/fS5n4TyqmqftwMj2Ebw0avsuDbuI9wVX4exUNiuQRru967QPrQinMuAwBGLCNYMs69ZHFBMkpk61khQGC3W7d5Yr/25HabnQBFpfO2llHhKKgM/Ckyqur+ku88EVJH9nRCDqOprJtC4RGHIA833ENL8xVP/VOvfiKG0Q14=
  gem: metadata-json-lint
  on:
    tags: true
    rvm: 2.7
    repo: voxpupuli/metadata-json-lint

notifications:
  email: false
  irc:
    on_success: always
    on_failure: always
    channels:
      - "chat.freenode.org#voxpupuli-notifications"
